#!/usr/bin/env Rscript
# This file is for identifying T1D SNPs occupied in RoadMap enhancers

## Command Arg Parameters ##
# Rscript src/bedtools_closest_roadmap.r data/roadmap_dist.tsv
args = commandArgs(trailingOnly=T)
hmsg = 'Rscript bedtools_closest.r [bedtools_closest_result_file_path]
  - Argument [bedtools_closest_result_file_path] is a mendatory file path including SNPs distance information generated by <bedtools closest> function.
  - [bedtools_closest_result_file_path]: data/roadmap_dist.tsv'
if(length(args)<1|length(args)>1) stop(hmsg)
path = unlist(args[1])

# System parameter
suppressMessages(library(tools))
suppressMessages(library(data.table))
suppressMessages(library(dplyr))
source('src/pdtime.r')
t0 = Sys.time()
dir = 'data/'
f.name = file_path_sans_ext(basename(path))

#########################
## Function start here ##
#########################
# 1. Compiling SNP data distant from RoadMap enhancers
rd = as.data.frame(fread(path))
cat(paste0('>> Table dim; rows = ',dim(rd)[1],', cols = ',dim(rd)[2],'\n'))
pos  = unlist(apply(rd,1,function(x) paste0(x[5],':',x[6],'-',x[7])))
rd_  = cbind(rd[,1:4],pos,rd[,8:9])
colnames(rd_) = c('chr','start','end','rsid','enh_pos','num','dist')
dis = rd_$dist %>% as.character %>% as.numeric
rd.df = cbind(rd_[1:6],dis); rd.df %>% head

# 2. Filtering SNPs by distance of closest enhancers
rd.df_ = unique(subset(rd.df,dis==0))
cat(paste0('Enhancer occupied by SNPs = ',length(unique(rd.df_$enh_pos)),'\n'))
cat(paste0('SNPs in RoadMap enhancers = ',length(unique(rd.df_$rsid)),'\n'))
f.path1 = paste0(dir,f.name,'_df.tsv')
write.table(rd.df_,f.path1,row.names=F,quote=F,sep='\t')
cat(paste0('\nFile write: ',f.path1,'\n'))

snp.bed = unique(rd.df_[,1:4])
n1 = length(unique(snp.bed$rsid))
f.path2 = paste0(dir,'snp_',n1,'_',f.name,'.bed')
write.table(snp.bed,f.path2,row.names=F,col.names=F,quote=F,sep='\t')
cat(paste0('File write: ',f.path2,'\n'))
cat(paste0('\n>> ',pdtime(t0,1),'\n'))
##################
## Function end ##
##################